### ISSUE TITLE
我的点赞/我的收藏/我的评论均为空白

### ISSUE THREAD

**Issue by Mushan3420** [dchijack/Travel-Mini-Program#2]
我的点赞/我的收藏/我的评论均为空白，查看API发现：
/wp-json/mp/v1/posts/comment?type=like&access_token=XXX
/wp-json/mp/v1/posts/comment?type=fav&access_token=XXX
/wp-json/mp/v1/posts/comment?type=comment&access_token=XXX
这三个API返回的结果均为 []

环境信息：
Nginx 1.17.8
MySQL 8.0.19
PHP 7.3.14
WordPress 版本 5.3.2
固定链接设置 /blog/%category%/%post_id%.html

**Comment by dchijack** [comment]
你的问题比较难排查。检查你的评论、点赞、收藏数据是否存在。

**Comment by Mushan3420** [comment]
> 你的问题比较难排查。检查你的评论、点赞、收藏数据是否存在。

检查过，都存在。并且，换默认主题，以及停用其他插件，也都试过了。

**Comment by dchijack** [comment]
评论，点赞，收藏都属于评论，分属不同的评论类型。你检查你的后台评论有没有内容列表。如果有对应的内容列表，但还是没有相关文章数据的话，这个就很难说了。目前没有收到更多关于这个空数据的反馈，不知道是不是个别的特例。

**Comment by Mushan3420** [comment]
> 评论，点赞，收藏都属于评论，分属不同的评论类型。你检查你的后台评论有没有内容列表。如果有对应的内容列表，但还是没有相关文章数据的话，这个就很难说了。目前没有收到更多关于这个空数据的反馈，不知道是不是个别的特例。

如前所述，数据都存在，也就是说，后台评论中是有内容列表的。

**Comment by dchijack** [comment]
根据其他用户的反馈，并没有这个情况。MySQL 版本 8.0 ，这个没有测试，不知道有没有关系。我下次更新一下插件，优化一下，到时再看看行不行吧

**Comment by Mushan3420** [comment]
> 根据其他用户的反馈，并没有这个情况。MySQL 版本 8.0 ，这个没有测试，不知道有没有关系。我下次更新一下插件，优化一下，到时再看看行不行吧

感谢更新，目前插件更新以后解决了。

另外一个问题，我也开了一个 issue，麻烦修复一下：
https://github.com/dchijack/Travel-Mini-Program/issues/3
